WellCommerce\Bundle\ContactBundle\Entity\ContactTranslation:
    type: entity
    table: contact_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
        email:
            type: string
            length: 255
            nullable: false
        phone:
            type: string
            length: 255
            nullable: false
        businessHours:
            type: text
            nullable: true
            column: business_hours
        line1:
            type: string
            length: 255
            nullable: true
        line2:
            type: string
            length: 255
            nullable: true
        postalCode:
            type: string
            length: 255
            nullable: true
            column: postal_code
        state:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 3
            nullable: true
