
services:
    contact.controller.admin:
        class: WellCommerce\Bundle\ContactBundle\Controller\Admin\ContactController
        arguments: ['@contact.manager', '@contact.form_builder.admin', '@contact.datagrid']
        calls:
            - [setContainer, ['@service_container']]

    contact.layout_box.configurator:
        class: WellCommerce\Bundle\LayoutBundle\Configurator\ContactBoxConfigurator
        tags:
            - { name: layout_box.configurator }
        arguments: [Contact, contact.layout_box.controller, '@translator.helper']
        calls:
            - [setContainer, ['@service_container']]

    contact.controller.front:
        class: WellCommerce\Bundle\ContactBundle\Controller\Front\ContactController
        arguments: ['@contact.manager', '@contact.form_builder.front']
        calls:
            - [setContainer, ['@service_container']]

    contact.layout_box.controller:
        class: WellCommerce\Bundle\ContactBundle\Controller\Box\ContactBoxController
        arguments: ['@service_container', '@contact.repository']

    contact.context.front:
        class: WellCommerce\Bundle\ContactBundle\Context\Front\ContactContext
