# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_doctrine:
    configuration:
        contact:
            factory: WellCommerce\Bundle\ContactBundle\Factory\ContactFactory
            repository: WellCommerce\Bundle\ContactBundle\Repository\ContactRepository
            mapping: "@WellCommerceContactBundle/Resources/config/doctrine/Contact.orm.yml"
            entity: WellCommerce\Bundle\ContactBundle\Entity\Contact
        contact_translation:
            manager: false
            mapping: "@WellCommerceContactBundle/Resources/config/doctrine/ContactTranslation.orm.yml"
            entity: WellCommerce\Bundle\ContactBundle\Entity\ContactTranslation
        contact_ticket:
            factory: WellCommerce\Bundle\ContactBundle\Factory\ContactTicketFactory
            repository: WellCommerce\Bundle\DoctrineBundle\Repository\EntityRepository
            mapping: "@WellCommerceContactBundle/Resources/config/doctrine/ContactTicket.orm.yml"
            entity: WellCommerce\Bundle\ContactBundle\Entity\ContactTicket
